In [1]:
import torch

In [151]:
max_len = 12
batch_size = 3
a = torch.rand([max_len, 1])
b = torch.rand([max_len, 1])
c = torch.rand([max_len, 1])

In [164]:
p = torch.cat((a, b), dim=1)

In [165]:
p

tensor([[0.8571, 0.2432, 0.2432],
        [0.9048, 0.1146, 0.1146],
        [0.0481, 0.8760, 0.8760],
        [0.7917, 0.5515, 0.5515],
        [0.3871, 0.7902, 0.7902],
        [0.5909, 0.1540, 0.1540],
        [0.6267, 0.7127, 0.7127],
        [0.4210, 0.5947, 0.5947],
        [0.9037, 0.3491, 0.3491],
        [0.4086, 0.3182, 0.3182],
        [0.6253, 0.0539, 0.0539],
        [0.0355, 0.0524, 0.0524]])

In [155]:
a.shape

torch.Size([12, 2])

In [141]:
a = torch.cat((t, b), dim=1)

In [142]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [143]:
a.shape

torch.Size([10, 2])

In [160]:
m = torch.rand([4,6])

In [161]:
m

tensor([[0.7789, 0.9322, 0.0976, 0.4305, 0.5396, 0.0896],
        [0.3545, 0.4025, 0.2900, 0.7499, 0.7317, 0.9266],
        [0.5334, 0.4995, 0.3635, 0.8497, 0.0373, 0.3004],
        [0.3697, 0.1748, 0.3476, 0.2895, 0.3465, 0.1895]])